name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2  # 检出代码

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # 部署到的分支
        folder: _site     # Jekyll 构建的输出目录
